### ISSUE TITLE
Joysticks of controllers are not supported

### ISSUE THREAD

**Issue by Jan200101** [FWGS/xash3d-android-project#104]
Title says it but to be clear:

Xash does not allow you to map Joysticks of any kind

**Comment by a1batross** [comment]
https://github.com/SDLash3D/xash3d/blob/master/engine/common/sdl/events.c#L217

Problem must be here. SDL2 can catch any type of button, but it just isn't mapped in the engine itself. If you know keycodes of buttons, you can add in a `switch` block and test it. If it will work, we will help you with merge request to develop branch. 

Available key defines are present in:
https://github.com/SDLash3D/xash3d/blob/master/engine/keydefs.h

**Comment by Jan200101** [comment]
You are telling me button but my two joysticks on my controller use (Left stick) AXIS_X AXIS_Y and (Right Stick) AXIS_Z AXIS_RZ with the highest value being 1 and the lowest -1. I have no Idea how I can add it into it but I hope you know how. Also I tested some controllers and all have a weird value as the default position so if you can add it then never accept any joystick input under 0.00 (like 0.001)

**Comment by Jan200101** [comment]
Okay I couldnt find the key code for the joysticks because they use axis but I can give you the keycodes for the dpad and the axises for both joysticks.

**Comment by a1batross** [comment]
Well. It's an old bug. Xash3D FWGS does noy use SDL2 on Android anymore. There is native Android gamepad code since summer 2016.
