### ISSUE TITLE
Request for detailed guide on compiling for Xash3D Android

### ISSUE THREAD

**Issue by CrustyBobcat** [FWGS/xash3d-android-project#108]
I've searched far and wide trying to figure out how to get Xash3D to compile, though
I keep getting stuck on each guide I find.

   I'm 90% sure I have all the tools and packages I need, I just don't know where to go now.
Running latest version of ubuntu, and I have android studio/sdk installed despite reading that you guys don't support it.

[how to compile? / como compliar?](https://github.com/SDLash3D/xash3d-android-project/issues/69#issuecomment-218098014)
   I've read over this as well as the solution a dozen times and still have trouble getting this working.

[Xash3D Engine on Raspberry Pi](https://www.raspberrypi.org/forums/viewtopic.php?f=78&t=115767&sid=3d1fc8519818f0299257518d279a5798&start=25)

> If anyone hasn't quite figured it out yet, I've gotten it to work (sort of) for the Raspberry Pi 2.

   Following this thread to get Xash3D running on the Raspberry Pi was the closest I came to building Xash3D, but even if I did get it to compile I wouldn't know how to make it into an APK for android.

[Building and running](https://github.com/SDLash3D/xash3d/wiki/Building-and-running)
Here I get confused because it says hlsdk only works on x86, while android is usually ARM based.
Though, on the raspberry Pi thread, they clearly use Cmake. Can't tell if they're actually using hlsdk or not. 

> Disable it by -DXASH_VGUI=no

Where is this command supposed to be entered at?

> For compiling, run git submodule init && git submodule update

   I haven't gotten this far, but I can't tell if I need to be in a certain folder or not, just need some clarification.

   I'm trying to get it working specifically for the Nvidia Shield TV, currently I have keyboard, and most of the controller working (no dpad or L2/R2) but for the life of me I can't get the mouse to work even after trying everything in this thread: [Capturing Mouse Positions](https://github.com/SDLash3D/xash3d-android-project/issues/87) There is also the issue of the gamepad not able to navigate the title screen if anyone has input on that.

   I was also interested in making a "Android TV app" that would allow you to select the mod you want on Xash3D since Android TV doesn't support shortcuts. Anyway, all of this being the main reason I even want to try and compile an edited version of the Xash3D for android.

   I appreciate any help, this engine has me pumped up and I've been dieing to get it working so that I may even be able to develop my own mods, though playing half-life on it is extremely cool in and of itself. Also wondering what you guys use to actually code the script itself,

**Comment by DeicPro** [comment]
Refer to:
```
git submodule init && git submodule update
```
Is used in project dir, for example:

If the project dir is in '/home/${USER}'
you need to do:
```
cd /home/${USER}/xash3d-android-project
git submodule init && git submodule update
```
For the issues you have got, share with us your console from https://gist.github.com for example (for not fill this with crap XD) and share link here to can help you saying what is the problem :).

Bad for sorry English.

**Comment by a1batross** [comment]
Android version is really easy to compile. You need an Android SDK, NDK,
Python, Git and free time.

At first, clone this repo.

Then, as Deic said, run "git submodule init && git submodule update". It
will download all required subprojects.

After you can run build itself. I recommend look to build.sh script or
.travis.yml for all build stages(ndk-build, makepak.py and ant debug).
After that you will have a file named xashdroid-debug.apk in bin/ folder.

Also, yes we have plans to support Android TVs(at first, Razer Forge TV).

You should look to branches in Git. We implemented some interesting
features(or implementing it now), for example: launcher redesign, game
package(libs) searcher and even Android native backend, instead of SDL2.

**Comment by DeicPro** [comment]
run this
```
android update project --path /home/bobcat/git/xash3d-android/xash3d-android-project
```
and try again

**Comment by CrustyBobcat** [comment]
`Error: The project either has no target set or the target is invalid.
Please provide a --target to the 'android update' command.
It seems that there are sub-projects. If you want to update them
please use the --subprojects parameter.
`

**Comment by a1batross** [comment]
There is a solution in a message. Just read it.

**Comment by CrustyBobcat** [comment]
`Error: Target id '/home/bobcat/git/xash3d-android/xash3d-android-project' is not valid. Use 'android list targets' to get the target ids.
root@bobcat-Scriptbuntu:/home/bobcat/git/xash3d-android/xash3d-android-project# android list targets
Available Android targets:
`

apparently I have no available android targets

**Comment by CrustyBobcat** [comment]
`root@bobcat-Scriptbuntu:/home/bobcat/git/xash3d-android/xash3d-android-project# android update project --path /home/bobcat/git/xash3d-android/xash3d-android-project --target android-23`

```
Updated project.properties
Updated local.properties
Updated file /home/bobcat/git/xash3d-android/xash3d-android-project/proguard-project.txt
It seems that there are sub-projects. If you want to update them
please use the --subprojects parameter.
root@bobcat-Scriptbuntu:/home/bobcat/git/xash3d-android/xash3d-android-project# 
```

alright, so is it built now? or do I need to update the subprojects?

**Comment by DeicPro** [comment]
No problem bro, anyone have got a fail XD.

A thing, build with
```
sh gen-version.sh travis build
python2 makepak.py xash-extras assets/extras.pak
ndk-build NDK_TOOLCHAIN_VERSION=4.8 XASH_SDL=1 SUPPORT_WEBP=false -j2 APP_CFLAGS="-w" APP_ABI="armeabi-v7a-hard"
ant debug
```
because project *build.sh* have got a1batross config with passphrase and zipalign stuff

**Comment by CrustyBobcat** [comment]
[Successful build log](https://gist.github.com/CrustyBobcat/1fadd665ddec2127f050858ceed1a528)

alright, hows that look?

**Comment by DeicPro** [comment]
If you want update them do it, I think that is not needed.

**Comment by DeicPro** [comment]
apparently is fine. Try to install the app (uninstall Xash3D if have installed already, because different sign).

**Comment by CrustyBobcat** [comment]
I launched it, and it loaded the menu, but when I went to the launch button it gave me this error;

_SDL ERROR

An error occurred while trying to start the application. Please try again and/or reinstall.

Error: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/in.celest.xash3d.hl-1/ base.apk"],nativeLibraryDirectories=[/data/app/in.celest.cash3d.hl-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libSDL2.so"_

**Comment by DeicPro** [comment]
Did you download submodules in project dir?

```
git submodule init && git submodule update
```

**Comment by CrustyBobcat** [comment]
yes, it just accepted the command without giving me any messages though. Ill try again and rebuild

**Comment by CrustyBobcat** [comment]
I tried building with just ./build.sh but it just makes an unsigned apk that I cant load.

**Comment by DeicPro** [comment]
Try to start again and do it all as says `.travis.yml`
https://github.com/SDLash3D/xash3d-android-project/blob/master/.travis.yml

**android sdk packages**
platform-tool
build-tools-21.1.1 (tick obsolete checkbox)
sdk platform api 13 (tick obsolete checkbox)
android support library (tick obsolete checkbox)
```
git clone https://github.com/SDLash3D/xash3d-android-project.git
cd xash3d-android-project
git submodule init && git submodule update
sh gen-version.sh travis build
python2 makepak.py xash-extras assets/extras.pak
ndk-build NDK_TOOLCHAIN_VERSION=4.8 XASH_SDL=1 SUPPORT_WEBP=false -j2 APP_CFLAGS="-w" APP_ABI="armeabi-v7a-hard"
android update project --path /home/bobcat/xash3d-android-project
ant debug
```
and share the cmd log if not works

**Comment by CrustyBobcat** [comment]
[Link](https://gist.github.com/CrustyBobcat/6aee834ee7e2fc4687072db5f6ac746b)
heres the log, headed to work. thanks for all the help guys!

**Comment by CrustyBobcat** [comment]
[Build Log After adding the sdk packages and finishing the commands](https://gist.github.com/CrustyBobcat/2503db1a0d05350ec40211e55332923f)
Alright, back from work, heres the updated log

**Comment by CrustyBobcat** [comment]
I had to update my jni/Application.mk file to change the toolchain from 4.8 to 4.9 manually, this allowed me to actually use the NDK build command
[NDK build with error](https://gist.github.com/CrustyBobcat/efbf1b346d7a1ecece843d5a43769309)

So now its giving me a new error to solve.

**Comment by CrustyBobcat** [comment]
[Finally did it!](https://gist.github.com/CrustyBobcat/639c8c4976367853375631b8e1818352)
So after an hour of looking over each of the android platforms, i finally got what it was missing and got it to compile successfully.

Thanks for all the great help guys, now I can finally start messing with the source

**Comment by lewa-j** [comment]
Close it?

**Comment by gr01d** [comment]
hey guys I am trying to port my old HL mod to android. I am currently stuck at trying to compile 'mod-sample'. I have downloaded the android-ndk-r10e, android-studio(AI-162.3934792),android-sdk (in ~/Android/sdk)
I installed ant using sudo apt install ant (debian 9.1 stretch)
I have installed/downloaded/unpacked android build tools (build-tools_r21.1.1-linux.zip,sdk platform api 13 ( android-3.2_r01.zip) to android/sdk directory) the error is the 
```

user@debian:/home/user/de/AND/mod-sample$ ./build.sh 
/home/user/de/android-ndk/build/core/build-all.mk:87: Android NDK: WARNING: No modules to build  your APP_MODULES definition is probably incorrect!   
rm -f ./libs/arm64-v8a/lib*.so ./libs/armeabi/lib*.so ./libs/armeabi-v7a/lib*.so ./libs/armeabi-v7a-hard/lib*.so ./libs/mips/lib*.so ./libs/mips64/lib*.so ./libs/x86/lib*.so ./libs/x86_64/lib*.so
make: *** No rule to make target `server', needed by `ndk-app-local'.  Stop.
make: *** Waiting for unfinished jobs....
rm -f ./libs/arm64-v8a/gdbserver ./libs/armeabi/gdbserver ./libs/armeabi-v7a/gdbserver ./libs/armeabi-v7a-hard/gdbserver ./libs/mips/gdbserver ./libs/mips64/gdbserver ./libs/x86/gdbserver ./libs/x86_64/gdbserver
rm -f ./libs/arm64-v8a/gdb.setup ./libs/armeabi/gdb.setup ./libs/armeabi-v7a/gdb.setup ./libs/armeabi-v7a-hard/gdb.setup ./libs/mips/gdb.setup ./libs/mips64/gdb.setup ./libs/x86/gdb.setup ./libs/x86_64/gdb.setup
Buildfile: /home/user/de/AND/mod-sample/build.xml

BUILD FAILED
/home/user/de/AND/mod-sample/build.xml:91: Cannot find /home/user/Android/Sdk/tools/ant/build.xml imported from /home/user/de/AND/mod-sample/build.xml
```

**Comment by a1batross** [comment]
@gr01d You need to port your changes from mod to ```hlsdk-xash3d```. Then you need to list all files you're used in Android.mk. (if you have created new file, then add it to corresponding Android.mk). 

Then move hlsdk-xash3d source code to jni/ folder of ```mod-sample``` project.

**Comment by gr01d** [comment]
@a1batross thanks for the info i have successfully build my mod for android. I just needed the old android sdk tools (tools_r25.2.5-linux) the newer one that i installed does not have the ant in the tools/ant/build.xml. 

anyone having problems I did the following steps:
use your favorite download manager( wget,curl,aria2,axel etc)
-downloaded https://dl.google.com/android/repository/tools_r25.2.5-linux.zip
-android studio for downloading platformtools api 13, build-tools-21.1.1,android sdk 3.2,sdk platform api 13.
```
$ export ANDROID_SDK=<pathtoextractredandroidsdk>/Android/Sdk/
$ export ANDROID_NDK=<pathtoextractredandroidndk>android-ndk/
$ export PATH="$PATH:$ANDROID_SDK/tools:$ANDROID_SDK/platform-tools:$ANDROID_NDK"
$ export ANDROID_HOME=<pathtoextractredandroidsdk>/Android/Sdk/
$ cd ~
$ git  clone https://github.com/FWGS/mod-sample
$ cd  mod-sample/jni && git clone https://github.com/FWGS/hlsdk-xash3d
$ cd ~/mod-sample && nano project-properties 
change android-5 to your target android ex. android-13
$ nano ./build.sh
comment out jarsigner and zipalign then save (ctrl+x y)
$ ./build.sh
done
$ adb install to your android
$ adb install bin/mod-sample.apk
```

**Comment by gr01d** [comment]
@a1batross the android port works. I am also trying to compile the server,client for xash3d 0.19 linux x86 using the cmake and make but for some reason the changes are not noticable in linux but works in the android apk. by using the  build.sh the modifications in  jni/hlhlsdk-xash3d are now generated in mod-debug.apk whatever changes I made it appears example changing the color of HUD adding Radar. I cd to jni/hlsdk-xash3d/build/dlls and execute make the same for jni/hlsdk-xash3d/cl_dll make copying the libclient and libserver to valve/dlls and cl_dlls. upon executing the xash.sh and playing the changes such as changing the hud color and radar does not appear at all.
there is a message in console that says: Error: CL_ParseUserMessage: HudRadar not hooked i have already added hudradar.cpp to cmakelist in cl_dll. however if I run the mod in android the radar and changed hud color are there. Please help.Thank You
