### ISSUE TITLE
Add Multi Language

### ISSUE THREAD

**Issue by wbsdty331** [FWGS/xash3d-android-project#109]
How to translate it into Chinese?

**Comment by a1batross** [comment]
Look up in res directory.
Create a "values-XX" folder, where XX is your language's code. Then copy a
strings.xml from values/ to created folder. Open it and translate, it's a
plain XML.

Note that strings marked "untranslatable="true"" must be erased.

**Comment by wbsdty331** [comment]
@a1batross
But I cannot change Language in app, I didn't find any options.

**Comment by a1batross** [comment]
0.17.1 doesn't have other language translations other than English or
Russian.

2016-07-23 21:31 GMT+06:00 Liu Yixuan <notifications@github.com>:

**Comment by wbsdty331** [comment]
You said:
> 0.17.1 doesn't have other language translations other than English or
Russian.

But I checked `/res/values-cn` folder, I found it included full translation XML file.

**Comment by a1batross** [comment]
So you can translate it. :)

There is values-zh folder. As I remember this is Chinese.

Closing it.
