### ISSUE TITLE
Click For Shot and Capturing Mouse Positions

### ISSUE THREAD

**Issue by dorcilio** [FWGS/xash3d-android-project#116]
I bought a USB OTG, but do not capture the mouse movement and the click.
I searched and found only tutorials using root.
Is there any way?

Regards,
Dorcílio Neto.

**Comment by mittorn** [comment]
It is possible to use mouse only on some Tegra devices, and it is not implemented yet.
Android does not allows applications to get relative mouse movement. Only absolute that clipped in screen rect.

**Comment by a1batross** [comment]
Using mouse is possible without root on NVIDIA SHIELD devices and(I don't tested it) on Android 7.x devices.
