### ISSUE TITLE
Game Crashes after player gets killed (CS 1.6 on Android)

### ISSUE THREAD

**Issue by KurutoColony** [FWGS/xash3d-android-project#117]
My game crashes after a bot kills me or the c4 kills me.
My device is Samsung Galaxy Tab 3 V
Version of Client: 1.01
When the game crashes this pops up:
![screenshot_2016-09-28-21-16-01](https://cloud.githubusercontent.com/assets/22539374/18984629/3961c9ce-8726-11e6-9716-96db4c2f76ef.png)

**Comment by mittorn** [comment]
Not related to xash3d-android-project
https://github.com/FWGS/cs16-client
By the way, you are using modified resources, this is not supported. Check it with original if possible before reporting bugs.
