### ISSUE TITLE
performance drop?

### ISSUE THREAD

**Issue by kuwoh** [FWGS/xash3d-android-project#118]
playing on the cs client and i noticed im only geting around 20~ish sometimes even below that fps
i used to get around 100+
this started happening since i updated xash3d
xash ver 0.18.1

device: SKK Chronos Ace
Android ver: 6.0
cpu: quad-core 1.3 ghz

**Comment by mittorn** [comment]
Try -casesensitive command-line option.
It seems, that new filesystem code works slower on android devices with fake sdcard.

**Comment by kuwoh** [comment]
thanks. it improved performance :smile:

**Comment by mittorn** [comment]
Note that it may cause some problems like missing some textures in opfor because of OPFOR.wad.
And it worked incorrectly before 0.18.1

I think, we need add check before enabling case-insenstiive.
But it will not help with android virtual sdcard because it case sensitive.
