### ISSUE TITLE
Xash Error when launching game directly from external SD Card

### ISSUE THREAD

**Issue by ishy123** [FWGS/xash3d-android-project#119]
command line arguments are  -dev -log, shows this: (can't find engine.log in xash folder so I had to take screenshots)
http://imgur.com/a/pZiDG

when I remove everything in the command line, it says that it couldn't find game directory valve even though its in the xash folder (same goes with cstrike when using cs16client)

device is samsung galaxy tab 3 7.0, rooted, running android 4.4.2
CPU: Dual-core 1.2 GHz Cortex-A9
GPU: PowerVR SGX540
1GB of ram

I would also like to note that I moved the xash folder from my SD card to my internal storage, and then it started to work. But, since the internal storage on my tablet is so small, I had to remove it.

**Comment by a1batross** [comment]
I heard that KitKat have a "feature" that don't allow apps write to SDCard.

Need to workaround this from code, but I couldn't find any docs for it.

I think, you can move game data to Android/data/in.celest.xash3d.hl/
folder, maybe it will work. Or just install these SD card write permission
fixes.

**Comment by a1batross** [comment]
In 0.19 launching engine with non-writable storage is prohibited.

Testing engine builds introduce new feature -- "RoDir". It can be used to read resources from read-only memory.

**Comment by ankitrathod1999** [comment]
Cs 1.6 client shows 'couldn't find game directory cstrike' though all the files are moved in the correct folder.
Also its a bit confusing doing all this in redmi 4. Pls help
