### ISSUE TITLE
[REQUEST] Adrenaline Gamer port to Android

### ISSUE THREAD

**Issue by CrusoeDaWolf** [FWGS/xash3d-android-project#123]
It would be really cool to see a full port of Adrenaline Gamer to Android.
An HL player by the name of YaLTeR made something called OpenAG which is an open-source re-implementation of Adrenaline Gamer's client library (http://github.com/YaLTeR/OpenAG)
It could bring new game-modes and features.

**Comment by nekonomicon** [comment]
But original agmod 6.6.6 is open https://github.com/martinwebrant/agmod

**Comment by CrusoeDaWolf** [comment]
Ah. I did not know that was released! Still, it would be cool to see AG on Android!

**Comment by mittorn** [comment]
ok, it is very easy to do

**Comment by CrusoeDaWolf** [comment]
Awesome! I will be waiting for a release c:

**Comment by nekonomicon** [comment]
Ready! 
https://github.com/nekonomicon/AdrenalineGamer-android/releases

**Comment by CrusoeDaWolf** [comment]
Nice! I will be trying it out on my HTC One M8! Thank you so much 👍
