### ISSUE TITLE
OTG mouse and Keyboard

### ISSUE THREAD

**Issue by Recee23** [FWGS/xash3d-android-project#126]
So i bought a OTG cable my tablet does not have root is there any way i can get the view point of character in game half life and half life blue shift to look based off mouse movement when i go into the game and use mouse the mouse is just an extension of finger to click on joystick to move around is there way to make mouse controll shooting and stuff like in the pc version of game?

Nexus 10 Tablet
Samsung OTG cable

**Comment by a1batross** [comment]
There is no way to use mouse without root.

**Comment by Recee23** [comment]
Darn :(

**Comment by mittorn** [comment]
Try contact google, maybe they fix this in next android versions
