### ISSUE TITLE
All static linking?

### ISSUE THREAD

**Issue by fuzun** [FWGS/xash3d-android-project#128]
I want 1 executable without any dll(exe needs to also include hl dlls). Is this possible? Which parts of the engine should I change if possible?

**Comment by a1batross** [comment]
At this moment you can't include every dll into engine. You can only define XASH_SINGLE_BINARY for engine, which just enables main() entry point.

**Comment by mittorn** [comment]
It is possible, but you need to modify engine and libraries.
Modify SV_LoadProgs, CL_LoadProgs and UI_LoadProgs, to call dll functions directly.
Modify LINK_ENTITY_TO_CLASS macro in server code to add code that will generate hashed map with functions at initialization (attribute constructor or c++ dynamic initializers).

**Comment by mittorn** [comment]
Modify ComNameForFunctiion to format text representatiin of given address with some magic prefix.
Modify Com_FunctionForName to find linkent in hashed map or decode text representation of address.

**Comment by mittorn** [comment]
Read compiler docs to find how to prevent symbol name conflicts (server cvar struct variables v.s engine cvar_t pointer variables). Maybe some #pragma help to omit it.

**Comment by fuzun** [comment]
@mittorn I am in fact want to do something for Nintendo 3ds. While I am doing some initial research, do you have any information about xash3d on 3ds?

*SDL is not usable, it should be ok since xash3d does not strictly need it.
*For opengl, can you make a quick look at https://github.com/cpp3ds/gl3ds project? I doubt that implementation fulfill what xash3d need.

**Comment by mittorn** [comment]
@fuzun xash3d uses 50-80 MB RAM in half-life.
You need to optimize memory usage to be able to run it.
Sdl can be easily replaced.
