### ISSUE TITLE
Mirror textures not working.

### ISSUE THREAD

**Issue by Bacte** [FWGS/xash3d-android-project#134]
Mirror textures (surfaces reflecting the environment) are working fine in the windows and linux ports, but in the android version the textures are rendered black, flashing white, depending the camera angle.

Tested with 2 different devices (Android 5.0.2, Mali 450 - Android 4.1.2, Adreno 305), same results.

Cvar gl_allow_mirrors is set to "1" in all tests.

**Comment by mittorn** [comment]
It is not supported, as glTexGen is hard to implement. You may implement it in nanogl (use qindiegl implementation as reference) and make pull request to nanogl repo.

**Comment by a1batross** [comment]
gl_allow_mirrors is deprecated now. It may be removed from both FWGS fork and original Xash3D.

They maybe will be restored in XashXT's custom renderer.
