### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by chinelosabio** [FWGS/xash3d-android-project#140]
Error: w_open cstrike/iga_static.wad unknown wad type
Error: FS_addwad_fullpath unable to load wad "cstrike/iga_static.wad"

![screenshot_2017-05-24-10-21-28](https://cloud.githubusercontent.com/assets/28064705/26405265/2e0f5ee8-406b-11e7-9274-1280e46fade0.png)

**Comment by thisisdark** [comment]
This is caused by iga_static.wad failing to download. This has nothing to
do with the client, and is not a bug.

>

**Comment by a1batross** [comment]
@thisisdark iga_static.wad is downloaded, but seems broken.

@chinelosabio Redownload iga_static.wad by removing file from cstirke/downloaded/. If error is being caused again, you should contact server administrator or just choose another server from list.
