### ISSUE TITLE
Crash after connecting keyboard and mouse

### ISSUE THREAD

**Issue by asymcon** [FWGS/xash3d-android-project#145]
Hi,
I'm trying to play using external mouse and keyboard, but xash3D crashes when any of those are connected via OTG. QIIA or QIIIA runs without issues.
Device is Redmi 4A running MIUI 8.5.1.0 and Android 6.0.1

Best,
asymcon

**Comment by mittorn** [comment]
What xash3d version do you have?

**Comment by asymcon** [comment]
v0.15
Apologies for delayed reply.
Since then the crashes stopped, but it's still not possible to use mouse as the pointer overlays the display and it behaves like a joystick controller, Turning is impossible - when I move the mouse the view spins around.

**Comment by a1batross** [comment]
v0.15 is two year old. 

Download v0.19 from Google Play or Github Releases.

**Comment by asymcon** [comment]
Tested v0.19, no crashes now, still mouse pointer overlays the screen and it's necessary to hold left mouse button to turn.
Any workaround for this? Should've mentioned the phone is rooted.

Thanks,
O.

**Comment by a1batross** [comment]
If so, you can use "evdev" feature, that just reads raw mouse data.

Set "evdev_mousepath /dev/input/eventN" cvar, where N is number to mouse
device.

Then enter "evdev_mouseopen", this will ask for root privileges and open
mouse device.

There is also "evdev_grab 1" to grab mouse pointer from Android and
"evdev_mouseclose" to close mouse device and try to open another.

Also, I did not tested it, but mouse may work automatically and without
root on NVIDIA SHIELD devices or starting from Android 7.x on other devices.

2 авг. 2017 г. 12:44 пользователь "asymcon" <notifications@github.com>
написал:

**Comment by mittorn** [comment]
If you want to play with mouse, download latest test version from github.com/fwgs/xash3d-deploy and use evdev_autodetect
