### ISSUE TITLE
Extended buttons support

### ISSUE THREAD

**Issue by D0ve** [FWGS/xash3d-android-project#152]
Уважаемые разработчики, включите пожалуйста в настройках  (кроме кнопок звука, которые уже поддерживаются) поддержку определения также и 3х тач кнопок андроида (аппаратных и програмных тоже, т.к. у многих Андроид-устройств вместо аппаратных - програмные),
 а также кнопку вкл/выкл! (т.е. выбор или как обычные в Андроиде, или определяются в Ксаше)
Заранее огромное спасибо за реализацию!

**Comment by a1batross** [comment]
Не вижу в этом смысла. Физических кнопок гарантированно лишь 3: Volume+, Volume- и Power. Последнюю вообще нельзя трогать. 

Ну и кстати говоря, навигационные кнопки вполне используются. Например, кнопка "Назад" используется как Escape.

**Comment by D0ve** [comment]
Кнопку Power чесно говоря хотелось бы иметь возможность использовать , да она критичная ,)  , но всегда же можно аккум отключить и перегрузиться ,  ну и предупреждение естественно выводить при её задействовании.
 Да и 3 навигационные кнопки тоже архинужны в игре !!! На них можно много чего повесить! -Переключение оружия, присесть и прыгнуть , да и много чего ещё !!!

 Просто, если в целом, имел в виду , что когда будет возможность задействовать все кнопки - больше возможности погружения в игру ! А все кнопки - это как раз и есть громкость+ , громкость- , питание  и  3 навигационные тач кнопки .
 Просто , когда тестирую какой-нибудь новый билд Ксаш-Андроид, пальцы сами на эти все кнопки тянутся ))) , особенно на 3 навигационные !!! То, что они частично используются не так к сожалению важно, важно иметь возможность их настроить как нужно для игры !

**Comment by D0ve** [comment]
И хотелось бы отдельно подчеркнуть, что не стоит опасаться возможности задействования всех кнопок , Андроид просто закроит сам Ксаш если произойдёт какая-либо ошибка , - и все кнопки имхо вернуться к своим обычным обязанностям!
Ну и аккумулятор всегда можно оключить если что!

**Comment by a1batross** [comment]
Вопрос не в том, опасаешься нет. Некоторые(к счастью) просто невозможно задействовать, вроде кнопки Power или Home. И с точки зрения пользователя это на самом деле неправильно.

**Comment by D0ve** [comment]
окей, ладно с power ,а что с 3мя навигационными тач кнопками ? Можно ли их задействовать , или хоть какие-нибудь из них?
Объясню почему, это не прихоть - они прямо сами просятся, чтобы ими играли !!!
'Живые' кнопки, такие как те же power или sound+- быстро могут быть сломаны, только потому, что они так устроены, так что в них и не поиграешь то толком!!!
А вот эти 3 навигационные тач-кнопки - они просто как-будто 'созданы специально' , чтобы их все 3 задействовать в игре!!! Тем более, что в игре почти всегда инстинктивно, к примеру у меня, нажимается одна из них)

**Comment by mittorn** [comment]
Меню задействовано и так. Back действительно можно задействовать., может это сделать какой-нибудь отдельной опцией Home андройд не даст занять вообще и обычно она посередине, так что особо не поиграешь.
Поставь xposed плагин на переназначение кнопок какой-нибудь

**Comment by D0ve** [comment]
Да, действительно , сам тоже подумал, что можно вначале поставить приложение переназначающее все три системные тач-кнопки. Или переназначить их т.н. ''ручным способом" на 'софт' кнопки на тач-скрине...
Можно ли будет после всего этого задействовать эти 3 тач-кнопки в Ксаше ?

**Comment by D0ve** [comment]
А можно задействовать функции из AccessibilityAPI, например ButtonMapper, чтобы задействовать три тач кнопки? Потому как правда нехватает дополнительных кнопок при игре и тем более они 'неубиваемые', т.е. как раз то что надо)
https://geektimes.ru/post/295397/

**Comment by mittorn** [comment]
Ты статью то эту читал? Помимо того что это нельзя использовать в google play релизах оно ещё и спровоцирует тупые антивирусы

**Comment by a1batross** [comment]
Напоминаю, что вопрос этот закрыт. Никаких новых **юзабельных** кнопок не появилось и не появится.
