### ISSUE TITLE
Broken test build

### ISSUE THREAD

**Issue by D0ve** [FWGS/xash3d-android-project#158]
Последний андроид-тестовый билд выдаёт ошибку при запуске игры. При этом само  меню запускается. И весит всего 2 мегА, в отличии от 7-ми :(.

**Comment by a1batross** [comment]
А ты не видишь, что Travis выдаёт статус Failed?

**Comment by a1batross** [comment]
Приду домой, закоммичу исправление. А то я сделал, но интернета не было и я не коммитил.

**Comment by D0ve** [comment]
Спасибо большое!

Есть ещё одно,- сейчас приходится удалять старый тестовый билд, чтобы поставить новый(((.
А можно что-нибудь сделать, чтобы можно было бы 'накатывать' новый тестовый билд на старый? (без необходимости удаления старого, а обновлением)

**Comment by a1batross** [comment]
Fixed.

Не надо ещё одно. Заводи новую ишшую каждый раз.
