### ISSUE TITLE
Possibility to update android test build

### ISSUE THREAD

**Issue by D0ve** [FWGS/xash3d-android-project#159]
Cейчас приходится удалять старый тестовый билд, чтобы поставить новый(((.
И при попытке установить обновление, выдаётся "приложение не установлено''.
  А можно что-нибудь сделать, чтобы можно было бы 'накатывать' новый тестовый билд на старый? (без необходимости удаления старого, а обновлением)

**Comment by mittorn** [comment]
Если есть возможность xposed, можно отключить проверку подписи.
Второй вариант - возьми приложение которое может переподписывать apk (например mt manager  или zipsigner) и подписывай им apk перед установкой.

**Comment by mittorn** [comment]
Если есть возможность поставить xposed, можно отключить проверку подписи.
Второй вариант - возьми приложение которое может переподписывать apk (например mt manager или zipsigner) и подписывай им apk перед установкой.

**Comment by a1batross** [comment]
Есть мысль сгенерировать ключ без пароля и им подписывать. Пусть лежит в
андроид проекте.

8 февр. 2018 г. 6:00 пользователь "mittorn" <notifications@github.com>
написал:

**Comment by mittorn** [comment]
Ну можно и так. Заодно врубить проверку на переподпись в качестве защиты от дурака

**Comment by a1batross** [comment]
Ты о certcheck? Стоит, да. Там как раз на будущее задел оставлен -- под тесты.

**Comment by a1batross** [comment]
Fixed.

**Comment by D0ve** [comment]
Спасибо! Ключ без пароля очень хорошая идея! 
Однако 'certcheck' хотел бы попросить убрать, т.к. для нескольких копий например это имхо будет мешать.

**Comment by a1batross** [comment]
Ничего не будет мешать. Не выдумывай ерунду.

**Comment by D0ve** [comment]
Ок, т.е. те же xposed , mt manager и zipsigner и т.д. будут с пакетом который с certcheck'ом нормально работать? Тогда не спорю;)

**Comment by a1batross** [comment]
Из выше приведеного говна я знаком только с первым. Об остальных не знаю. Да и не обязано оно работать для мамкиных кулхацкеров.

**Comment by D0ve** [comment]
Просто хочу отстоять мысль, что "проверка на переподпись в качестве защиты от дурака" (certcheck) не нужна , т.к. возможность устанавливаль беспроблемно несколько копий например будет затруднительна (для целей того же тестирования, с разными настройками)

**Comment by a1batross** [comment]
Не нужна. Вам незачем копаться внутри, вы -- не разработчик. А других целей я не вижу.

**Comment by mittorn** [comment]
Он про установку нескольких копий, тут certcheck и правда мешает

**Comment by a1batross** [comment]
Я считал, что он читает содержимое коммитов...

Прекрати, Dove, разводить ТУПНЯК на ровном месте. Ты читал коммиты? Где там
тебе certcheck врубился? НЕТ ЕГО.

Он есть в релизных сборках. Потому что это блин релизные сборки и проблемы
инвалидов там никого не интересуют.
Здесь ими попросту заниматься некому и некогда. Так что отставить нытьё по
пустому месту.

**Comment by D0ve** [comment]
Содержимое коммитов читаю, сейчас только не читал. Вопрос снят). Всё имхо как нужно. Не судите строго).
