### ISSUE TITLE
XashService

### ISSUE THREAD

**Issue by D0ve** [FWGS/xash3d-android-project#160]
Что делает демон XashService?   ...к слову, не выгружается и висит в памяти(
Если сбор статистики, проверку новых версий и обновление...,-
просьба ввести расширенную опцию "не загружать службу сервиса XashService".
Заранее признателен.

**Comment by a1batross** [comment]
Оно для того, чтобы Android не закрывал процесс движка в своём жизненном цикле Activity. С Service это работает почти как на ПК.

**Comment by a1batross** [comment]
Нет, так никогда не будет. Это не обсуждается. 

Правильно выходить куда правильнее для движка, чем ваши личные хотелки.

**Comment by D0ve** [comment]
Просто основная суть хотелки в том, что сервис сам не выгружается после закрытия приложения (а при выходе выбрасываетмя ессно в загрузчик), и сервис висит постоянно в задачах (((. Можно ли сделать, чтобы он сам выгружался по закрытию приложения ?
И если проблемно, хотел предложить альтарнативу в качестве опции 'продвтнутых' настроек 'загружать/незагружать сервис' в загрузчике! Чтобы когда по exit'у выбросит в загрузчик, можно было бы выключить сервис(чтобы применилось бы тут же) и спокойно закрыть сам загрузчик из диспетчера.
 Ну и чтобы можно было так же глобально выключить этой же кнопкой загрузку сервиса на последних версиях андроида, где фоновые процессы не прибиваются.

**Comment by a1batross** [comment]
Если уведомление не висит, значит сервис и не запущен.

**Comment by D0ve** [comment]
Уведомление не висит, но в задачах (настройки -> приложения -> работающие) его вижу !

**Comment by a1batross** [comment]
Значит не запущен.

**Comment by mittorn** [comment]
@D0ve скрин можешь показать?
