### ISSUE TITLE
About the SD Card support.

### ISSUE THREAD

**Issue by Lion4K** [FWGS/xash3d-android-project#165]
Sorry to bring this up again, but I was trying GZDoom for android, and I noticed that they have implemented that feature that lets you manipulate the SD card under newer android versions.

I'm gonna let their Git here in case you wanna see if its feasible to implement or something like that.

https://github.com/nvllsvm/GZDoom-Android/releases

In their approach, they do like other apps like screen recorders and save their files under sdcard/Android/Data instead of letting one choose a folder at random on the sdcard.

**Comment by a1batross** [comment]
It was only supported way before 0.19.1

The new way, which is may be less compatible with Half-Life mods, but more powerful is RoDir.

**Comment by nekonomicon** [comment]
Seems Android 5.0+ feature. Too bad.
https://github.com/nvllsvm/GZDoom-Android/commit/dd730c6a5634e8cdbea1ad064651583a8fc49de8

**Comment by Lion4K** [comment]
Yeah its for android 5+ Devices that locked down access to SdCard.

**Comment by Lion4K** [comment]
Yeah RoDir is only good for main HalfLife campaing at this point.

**Comment by Lion4K** [comment]
Maybe this way would work better, i mean, the other way I suggested was acquiring permission to write anywhere on the SD Card.

This one is different, it uses an Android/Data folder which the app and only that app have full access and control over it, this might work better than RoDir.

What you think?

**Comment by a1batross** [comment]
You still can create Android folder hierarchy(Android/data/in.celest.xash3d.hl/files) on your SD card and point to it.

**Comment by Lion4K** [comment]
And since when this is possible?

**Comment by Lion4K** [comment]
I was not informed of this on the last issue I opened regarding this.

**Comment by Lion4K** [comment]
Btw works flawlesly, way better then RoDir

**Comment by a1batross** [comment]
@Lion4K it was possible since it's possible to change game directory to all. ;)
But this solution is destructive. If you will delete Xash3D FWGS app, Android will remove "in.celest.xash3d.hl" directory too.

RoDir is experimental and will be so forever. Just because engine does not expose internal filesystem utilities enough and modmakers may use C standard I/O or C++ I/O streams.

It may be handy in standalone games. I planned to use RoDir for Paranoia mod to use readonly content from OBB archive, as I have permission to post Paranoia game data to Google Play.

**Comment by Lion4K** [comment]
I can safely say:
![image](https://user-images.githubusercontent.com/10391955/38333295-938c594a-382e-11e8-8059-321a29a196c9.png)


All this time I was banging my head on the wall trying to figure out a way to play from SDCard as RoDir only worked for Valve and not for other mods, and it was already there, only no one bothered telling me.

So what the folder goes away when you uninstall the engine?
You can simply tell ppl to backup the folder beforehand.

But thanks I glad you let me know about this feature, now I can play all the mods from SD Card.
I can play any mod with this feature. Can even use VR (well I've tested but don't remember the command to activate the VR mode).

One more time thanks.
