### ISSUE TITLE
Android mods

### ISSUE THREAD

**Issue by BIGmane** [FWGS/xash3d-android-project#167]
Hello! I tried to use mods in the Android port of Xash3D. I put the mod folder in in the xash folder put the command line in. Started the game but IT didn't work. Can you please help me with this? Thank

**Comment by nekonomicon** [comment]
Which mods?
Provide more information.

**Comment by BIGmane** [comment]
Counter-Life. I read this mod is compatible with the Xash3D engine.

**Comment by nekonomicon** [comment]
Counter-Life has custom game libraries and working correctly on windows only.
You can run mods which does not have custom game libraries(client.dll and hl.dll) via Xash3D FWGS launcher without troubles.
If you want to run Counter-Life then needed port this mod separately, but mod author not released source code.

**Comment by a1batross** [comment]
Invalid. Closing.
