### ISSUE TITLE
Weapon Texture Bug in Xash3D FWGS 0.19x

### ISSUE THREAD

**Issue by AkiroGT** [FWGS/xash3d-android-project#177]
I have these weird Bugs in the weapon's texture that is missing or incomplete texture. For example Shield Glitch it's like transparent now but enemies still can't hit me if i cover Shield.. I need help about this bug, Also Xash3D 0.17x doesn't have weapon bugs. But crashes Sometimes. If any Help/HowtoFix please Comment.

**Comment by mittorn** [comment]
What texture?

**Comment by a1batross** [comment]
Screenshot maybe, at least?

**Comment by AkiroGT** [comment]
well i'm using an android device and i don't know how to send screenshots in here.. btw my english is bad right?

**Comment by AkiroGT** [comment]
i don't know how to say it right but skin/texture of any weapon is like missing some parts of it. That's like a half Desert Eagle or something.. It happens whenever i update to the latest version of Xash3D FWGS.

**Comment by mittorn** [comment]
Open desktop version to attach screenshot

**Comment by AkiroGT** [comment]
![screenshot_20180723-215022](https://user-images.githubusercontent.com/41581135/43361754-2c723ecc-930b-11e8-8c4c-be18078afa7a.png)

![screenshot_20180723-215030](https://user-images.githubusercontent.com/41581135/43361759-3f025036-930b-11e8-9831-3163609a69c8.png)

**Comment by a1batross** [comment]
You should install latest CS16Client and latest Xash3D FWGS. Both available at Google Play. 

Then set "hand 0" in console.

**Comment by AkiroGT** [comment]
![screenshot_20180729-171739](https://user-images.githubusercontent.com/41581135/43364861-91187036-9355-11e8-8116-f863d3a424d0.png)

I did what you said but I have another issue but I don't know if it is part of the Game, but take a look at this Screenshot.

**Comment by AkiroGT** [comment]
blue bulletholes and somekind of blacksmoke, whenever I hit the wall. some of the blue dots float when I kill an enemy. is there any help to fix this? ( The First Issue was fixed. thx so much! )

**Comment by mittorn** [comment]
Just clean your configs. It is not related to engine or android project

**Comment by mittorn** [comment]
remove config.cfg. It will be generated automaticly with default values

**Comment by AkiroGT** [comment]
Ok, I deleted config.cfg but why won't it remove the bluedots and smoke? it is still there...

**Comment by AkiroGT** [comment]
I think it's because I added another cfg file called "ping.cfg" because my fps was low, and I don't know what ping.cfg do to Counter Strike

**Comment by a1batross** [comment]
Just. Install. Latest. CS16Client. =/

**Comment by AkiroGT** [comment]
yes, it is latest version

**Comment by a1batross** [comment]
Stop lying. It was fixed in 1.33.

**Comment by AkiroGT** [comment]
it is still bugged also in spectate mode  (no name)

**Comment by AkiroGT** [comment]
Oh! sorry i think i downloaded 1.32 ... it was in google play right?

**Comment by AkiroGT** [comment]
status update: i just recently updated to 1.33 the bulletholes are now normal. But the blacksmoke thing are not... i just noticed in folder /cstrike/resources And found 4 files that starts with BlackSmoke. I don't know what to do with it but im pretty sure that's causing it.

**Comment by a1batross** [comment]
Meh... 

Enter "fastsprites 0" to console.

And don't even touch configs! You may remove them to set default and that's all. Almost no one knows how engine and client is working, so shitty "boost your ping" will never work.

Also make sure, that you have downloaded game files from licensed Steam version of game. If it's not, you're not allowed to play.
