### ISSUE TITLE
Custom HD Weapon Skins Crashes My Game/Xash FWGS 

### ISSUE THREAD

**Issue by AkiroGT** [FWGS/xash3d-android-project#179]
i'm gonna make this quick.. Whenever i get some new skins for my weapon's the game crashes :p tell me how can i fix this. and i also know you're gonna ask why i downloaded skins for cs 1.6, it's becuase i get too boring of the normal guns so i decided to get some new ones. That's all. Hoping for a Reply Soon ._.

**Comment by a1batross** [comment]
Custom skins for CS16Client are not supported. You're on your own.

**Comment by AkiroGT** [comment]
that's not helpfull at all...
