### ISSUE TITLE
Crosshair problems maybe i shoot 1 cm above the crosshair is there any fix?

### ISSUE THREAD

**Issue by AkiroGT** [FWGS/xash3d-android-project#181]
I'm on a rush.. im using xash3D Latest and Cs16Client Latest, all i need is help how to fix this? it is annoying that i get headshots always XP but still i don't want it. If any help, thx in advance.

**Comment by a1batross** [comment]
viewsize 140

**Comment by AkiroGT** [comment]
thanks!, but now I got this problem. I got 2 crosshairs now whenever I play LAN Games with my friend's server. the CS crosshair and the Half-Life crosshair... when AWP it has a crosshair even if not in scope XD.

**Comment by a1batross** [comment]
It's a CS16Client known bug and already fixed for upcoming 1.4.
