### ISSUE TITLE
PAKs

### ISSUE THREAD

**Issue by rust2** [FWGS/xash3d-android-project#194]
How to make .PAK file?
And how to extract it?

**Comment by a1batross** [comment]
Well, this is kinda wrong place to ask questions(better to post them to FWGS/xash3d-fwgs next time) but I suppose you're asking about Android-only solutions.

We have makepak.py Python script, you can execute it in Python interpreter in Termux for example.

I didn't heard about any extracting tools on Android. But I think you can compile HLLib(in same Termux) and use HLExtract tool provided with it. I personally use GCFScape, under Wine if on Linux.

**Comment by rust2** [comment]
Where i can get HLLib?

**Comment by a1batross** [comment]
http://nemesis.thewavelength.net/index.php?p=35

**Comment by rust2** [comment]
Oh.. I cant build it because I haven't enough space on my phone

**Comment by rust2** [comment]
So thx for help

**Comment by nekonomicon** [comment]
>I didn't heard about any extracting tools on Android. But I think you can compile HLLib(in same Termux) and use HLExtract tool provided with it. I personally use GCFScape, under Wine if on Linux.Hmm... 

Hmm... Why not use nwreckdum?

**Comment by rust2** [comment]
@nekonomikon,  thx, it helped me

**Comment by rust2** [comment]
@nekonomikon, thx, it helped me very much

**Comment by rust2** [comment]
@nekonomikon thx, it helped me very much

**Comment by rust2** [comment]
@nekonomicon, thx, it helped me very much

**Comment by rust2** [comment]
So i can create .pak with "makepak.py" and extract it with"nwreckdum", thx 4 help
