### ISSUE TITLE
It is not possible to paste text from the clipboard into the console or chat.

### ISSUE THREAD

**Issue by AcidBurn9** [FWGS/xash3d-android-project#52]

**Comment by AcidBurn9** [comment]
With standart Samsung Keyboard.

**Comment by FalconTR** [comment]
You can use "Clipboard" by holding the button near to comma/spacebar. Or you can download alternative keyboard I recommend "play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard". You can ctrl+c/v in this keyboard.

**Comment by AcidBurn9** [comment]
No. That buttonn, near the space bar is not working. Console writing *keynum (very big number) out of range. And alternative ketboard SUCKS. Pls just fix that bug.

**Comment by a1batross** [comment]
Works now. Closing,
