### ISSUE TITLE
Cannot navigate menu with Nvidia Shield TV Controller + a few other things.

### ISSUE THREAD

**Issue by CrusoeDaWolf** [FWGS/xash3d-android-project#54]
I cannot seem to navigate the menu with my Nvidia Shield TV controller, however, I can do it perfectly fine with the remote. Also, I cannot switch weapons in game either, which makes it almost unplayable.

Device: Nvidia Shield TV
Android OS: Lollipop (5.1.1 I believe).

**Comment by stgarf** [comment]
I have a related issue with CS16Client: SDLash3D/cs16-client#140

**Comment by mittorn** [comment]
Did you try to bind buttons in keyboard menu?

**Comment by stgarf** [comment]
@mittorn Can you be more specific -- what keyboard menu are you talking about? The shield doesn't technically have a keyboard... I'll have to wait until I get home to check if you mean within xash3d itself.

**Comment by mittorn** [comment]
Try set m_ignore to 0 in config.cfg and navigate with mouse pointer in menu

**Comment by Jan200101** [comment]
A dev told me on how to use a controller.

Start normal Xash and uncheck the use volume buttons ( they mixed it up so unchecking is turning it on) then go and launch xash with half life or counter strike.
Go to controlls in the option and go to something like shoot. Now press volume up or down (forgot which it was ) and press any key on the controller. 

Also Joysticks wont work

**Comment by mittorn** [comment]
Which buttons are availiable on controller?

**Comment by stgarf** [comment]
I haven't had a chance to circle back to this, but this is what the controller looks like:
http://images10.newegg.com/ProductImage/34-762-005-19.jpg

Besides the buttons you can see on the front (home/playPause/back/and the green nvidia button), there are L1/R1 and L2/R2 buttons on the back.

**Comment by Jan200101** [comment]
Every button that has just one state (no r2 l3 or joysticks) is mappable yet I am going to make a Issue of that

**Comment by a1batross** [comment]
Fixed since 0.18.
