### ISSUE TITLE
Android menu buttons visible in Cardboard mode

### ISSUE THREAD

**Issue by sotrajohnny** [FWGS/xash3d-android-project#59]
Android navigation buttons are visible on the right of the screen when in cardboard mode
![2016-02-03 08 03 42](https://cloud.githubusercontent.com/assets/11884023/12776415/1746d9ac-ca56-11e5-9ca4-3f08bd6ff27d.png)
That makes them visible in one eye when using cardboard.

This is on Xperia Z3+

**Comment by ALoGeNo** [comment]
When you set VR mode you must deactivate touch controls.

**Comment by sotrajohnny** [comment]
I do not mean the touch controls but the white android buttons to the right (square, house, triangle)

**Comment by a1batross** [comment]
Check "Immersive Mode" in the settings.
