### ISSUE TITLE
Can't open in VR mode

### ISSUE THREAD

**Issue by Trolldozer128** [FWGS/xash3d-android-project#60]
In the v17 build, I cannot open the game in VR mode, I use the ARG Command Line -vrmode 1 but it does not work. Can someone please tell me how to open the game in VR mode in some other way?

**Comment by ALoGeNo** [comment]
Run with normal command line options, go to Configuration>Video>Video Options>Activate VR.

Cheers.

**Comment by Trolldozer128** [comment]
Well, I should've expected this. I never thought they would've edited the menu. But then again, there's the touch controls. Now to find out how to make the game work with a PS4 controller that's connected by Bluetooth. Thanks, though.

**Comment by ALoGeNo** [comment]
When you are in VR mode you must deactivate touch controls, I have my sixaxis running but I need to configure buttons and so on.

**Comment by a1batross** [comment]
VR mode is removed from engine and implemented in separate engine build: https://play.google.com/store/apps/details?id=in.celest.xash3dVR.hl
