### ISSUE TITLE
Showing status bar on Android OS 2.3.x

### ISSUE THREAD

**Issue by EXL** [FWGS/xash3d-android-project#62]
Good job, guys!

I checked the Xash3D v0.16.1 performance on my two old Android OS 2.3.x Motorola QWERTY-smartphones.

Report:

**Motorola Droid/Milestone 1st generation**
_2009, CyanogenMod 7, Android 2.3.7
TI OMAP 3430, 550 MHz, 256 RAM, PowerVR SGX530_:
~15-20 fps, in complex scenes drops sharply. Most crashes happen when level loading, I suspect there is not enough memory, then it just 256 MB. Xash3D can hardly be called playable on this device.

**Motorola Droid/Milestone 2st generation**
_2010, Official Android 2.3.4
TI OMAP 3630, 1000 MHz, 512 RAM, PowerVR SGX530_:
~39-49 fps, in complex scenes falls to 12-15. No crashes, playable.

![Droid 1 and Droid 2](http://wstaw.org/m/2016/02/16/IMG_20160216_144836_088.jpg)

**Defect on Android OS 2.3.x (on Android 4.1.x and higher all good) which need to be fixed:**
The Xash3D does not run in full-screen, status bar is remains on display.

Maybe something in Activity _onCreate()_:

``` java
/* We like to be fullscreen */
getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
                     WindowManager.LayoutParams.FLAG_FULLSCREEN);

requestWindowFeature(Window.FEATURE_NO_TITLE);
```

or something this in xml-styles for 2.3.x or _AndroidManifest.xml_:

``` xml
android:theme="@android:style/Theme.NoTitleBar.Fullscreen"
```

**Comment by mittorn** [comment]
We know about this defect, but enabling fullscreen  causes SDL to detect wrong screen size, so fullscreen forced to be disabled on 2.3.
https://github.com/SDLash3D/xash3d-android-project/blob/master/src/org/libsdl/app/SDLActivity.java#L159
I have not managed to fix similar bug in microemulator.
Did you tested these workarounds?

**Comment by mittorn** [comment]
We know about this defect, but enabling fullscreen  causes SDL to detect wrong screen size, so fullscreen forced to be disabled on 2.3.
https://github.com/SDLash3D/xash3d-android-project/blob/master/src/org/libsdl/app/SDLActivity.java#L159
I have not managed to fix similar bug in microemulator.
Did you tested these workarounds?

**Comment by mittorn** [comment]
We know about this defect, but enabling fullscreen  causes SDL to detect wrong screen size, so fullscreen forced to be disabled on 2.3.
https://github.com/SDLash3D/xash3d-android-project/blob/master/src/org/libsdl/app/SDLActivity.java#L159
I have not managed to fix similar bug in microemulator.
Did you tested these workarounds?

**Comment by mittorn** [comment]
We know about this defect, but enabling fullscreen  causes SDL to detect wrong screen size, so fullscreen forced to be disabled on 2.3.
https://github.com/SDLash3D/xash3d-android-project/blob/master/src/org/libsdl/app/SDLActivity.java#L159
I have not managed to fix similar bug in microemulator.
Did you tested these workarounds?

**Comment by mittorn** [comment]
We know about this defect, but enabling fullscreen  causes SDL to detect wrong screen size, so fullscreen forced to be disabled on 2.3.
https://github.com/SDLash3D/xash3d-android-project/blob/master/src/org/libsdl/app/SDLActivity.java#L159
I have not managed to fix similar bug in microemulator.
Did you tested these workarounds?

**Comment by mittorn** [comment]
We know about this defect, but enabling fullscreen  causes SDL to detect wrong screen size, so fullscreen forced to be disabled on 2.3.
https://github.com/SDLash3D/xash3d-android-project/blob/master/src/org/libsdl/app/SDLActivity.java#L159
I have not managed to fix similar bug in microemulator.
Did you tested these workarounds?

**Comment by mittorn** [comment]
We know about this defect, but enabling fullscreen  causes SDL to detect wrong screen size, so fullscreen forced to be disabled on 2.3.
https://github.com/SDLash3D/xash3d-android-project/blob/master/src/org/libsdl/app/SDLActivity.java#L159
I have not managed to fix similar bug in microemulator.
Did you tested these workarounds?

**Comment by mittorn** [comment]
We know about this defect, but enabling fullscreen  causes SDL to detect wrong screen size, so fullscreen forced to be disabled on 2.3.
https://github.com/SDLash3D/xash3d-android-project/blob/master/src/org/libsdl/app/SDLActivity.java#L159
I have not managed to fix similar bug in microemulator.
Did you tested these workarounds?

**Comment by mittorn** [comment]
We know about this defect, but enabling fullscreen  causes SDL to detect wrong screen size, so fullscreen forced to be disabled on 2.3.
https://github.com/SDLash3D/xash3d-android-project/blob/master/src/org/libsdl/app/SDLActivity.java#L159
I have not managed to fix similar bug in microemulator.
Did you tested these workarounds?

**Comment by mittorn** [comment]
We know about this defect, but enabling fullscreen  causes SDL to detect wrong screen size, so fullscreen forced to be disabled on 2.3.
https://github.com/SDLash3D/xash3d-android-project/blob/master/src/org/libsdl/app/SDLActivity.java#L159
I have not managed to fix similar bug in microemulator.
Did you tested these workarounds?

**Comment by mittorn** [comment]
We know about this defect, but enabling fullscreen  causes SDL to detect wrong screen size, so fullscreen forced to be disabled on 2.3.
https://github.com/SDLash3D/xash3d-android-project/blob/master/src/org/libsdl/app/SDLActivity.java#L159
I have not managed to fix similar bug in microemulator.
Did you tested these workarounds?

**Comment by mittorn** [comment]
We know about this defect, but enabling fullscreen  causes SDL to detect wrong screen size, so fullscreen forced to be disabled on 2.3.
https://github.com/SDLash3D/xash3d-android-project/blob/master/src/org/libsdl/app/SDLActivity.java#L159
I have not managed to fix similar bug in microemulator.
Did you tested these workarounds?

**Comment by mittorn** [comment]
We know about this defect, but enabling fullscreen  causes SDL to detect wrong screen size, so fullscreen forced to be disabled on 2.3.
https://github.com/SDLash3D/xash3d-android-project/blob/master/src/org/libsdl/app/SDLActivity.java#L159
I have not managed to fix similar bug in microemulator.
Did you tested these workarounds?

**Comment by mittorn** [comment]
We know about this defect, but enabling fullscreen  causes SDL to detect wrong screen size, so fullscreen forced to be disabled on 2.3.
https://github.com/SDLash3D/xash3d-android-project/blob/master/src/org/libsdl/app/SDLActivity.java#L159
I have not managed to fix similar bug in microemulator.
Did you tested these workarounds?

**Comment by mittorn** [comment]
We know about this defect, but enabling fullscreen  causes SDL to detect wrong screen size, so fullscreen forced to be disabled on 2.3.
https://github.com/SDLash3D/xash3d-android-project/blob/master/src/org/libsdl/app/SDLActivity.java#L159
I have not managed to fix similar bug in microemulator.
Did you tested these workarounds?

**Comment by mittorn** [comment]
f*ck

**Comment by a1batross** [comment]
Must be fixed in remove-sdl branch.

**Comment by EXL** [comment]
> Must be fixed in remove-sdl branch.

Yes, in the non-SDL version everything is fine, thank you.

![device-2017-01-01-173808](https://cloud.githubusercontent.com/assets/232116/21580872/27cc415e-d00e-11e6-9a78-bb4544301ad5.jpg)

Please close the issue.
