### ISSUE TITLE
Game do not Start LG G4

### ISSUE THREAD

**Issue by ras66** [FWGS/xash3d-android-project#65]
After choose "New Game" and "Medium" , the Game did not start. . Game Data is copied to "Valve"
LG G4 Android 6.0

**Comment by a1batross** [comment]
Maybe you did something wrong? Look some tutorial videos on YouTube and try again.

**Comment by ras66** [comment]
I do not know, what is wrong. v0.16.01 or v0.17beta did not start a New Game. I only see a black screen with the "Half life icon". Original Data is copied to /storage/emulated/0/xash/valve.
Xash-Extras ist copied. First, the Game missed the file "delta.lst", now it ist copied.
But nothing happens, only Black Screen

**Comment by a1batross** [comment]
What original data? 
You must copy valve folder from Steam HL release to /storage/emulated/0/xash/, so directory tree must look like:
```
xash/
├──valve/
   ├──maps/
      ├──<some map>.bsp
      ├──<some map2>.bsp
   ├──models/
      ├──<some model>.mdl
   <etc>
├──mod/
    ├──<same mod structure>
```

**Comment by ras66** [comment]
/Valve ist copied from the original CD (eng) 1998
Thanks for the help

**Comment by ras66** [comment]
a new installation of /Valve : no result

**Comment by a1batross** [comment]
Try to remove gameinfo.txt or check map names. 

Try to load map via console.

**Comment by ras66** [comment]
the console does not work. Only a black screen, the keystrokes are ignored.
The program crashes after starting a new game (with gameinfo.txt),
or do nothing (without gameinfo.txt)

**Comment by mittorn** [comment]
Smth wrong with your game files

**Comment by ras66** [comment]
That was right. A other Version of /Valve , and it runs. A cd of 1998 is too old. Thanks
