### ISSUE TITLE
[Suggestion] Fix for issue #58

### ISSUE THREAD

**Issue by leopard20** [FWGS/xash3d-android-project#66]
I understand that you have added an option to the engine (Touch_fl_precision) which partially fixes issue #58 (thanks to @a1batross for letting me know!). But, as you know, with this option you can only slow down aiming when a button is pressed.
I suggest that you add an option to the engine so that it distinguishes between tapping and swiping across the screen. 
For example, if the touch button is held for more than, say 20 milliseconds, after I drag my finger on the screen, it's a swipe gesture and the aim should move, otherwise it's tapping and the aim should stay still. 
Another alternative is the drag amount. For example if I drag on the screen for more than 50 pixels across (on a FullHD, 5 inch display), it's a swipe gesture, otherwise it's tapping.
But again I don't know much about Android programming and this may not be possible. But this is the only thing I can think of that fixes the aiming problem completely.

**Comment by mittorn** [comment]
It is possible, but someone need to debug it.
My device's touchscreen driver do such thing, so i cannot test it.
I'll try to implement this after 0.17 stable release.
maybe it will be configured by touch_look_threshold and touch_look_threshold_time cvars.

**Comment by a1batross** [comment]
Should  be fixed with "look_filter" cvar.
