### ISSUE TITLE
xash Japanese translation file

### ISSUE THREAD

**Issue by seojunrr** [FWGS/xash3d-android-project#79]
In order to XASH3D spread widely in the world.I made this file.Please add this Japanese translation file  (But I'm not Japanese.I'm Korean.But for the xash)

**Comment by a1batross** [comment]
Which file?

**Comment by seojunrr** [comment]
https://www.dropbox.com/s/fujtwj1pbtkdli1/strings.xml?dl=0        I edited

**Comment by seojunrr** [comment]
https://www.dropbox.com/s/fujtwj1pbtkdli1/strings.xml?dl=0       I edited sorry

**Comment by a1batross** [comment]
Why you are translated commits? 
They are generated on every build.

**Comment by a1batross** [comment]
Reopen this as a Pull Request and... don't touch non-translatable strings. :)
