### ISSUE TITLE
Touchscreen buttons too large for larger screens.

### ISSUE THREAD

**Issue by The-MAZZTer** [FWGS/xash3d-android-project#81]
There are a lot of great options in the Half-Life menus for adjusting the touch controls, but one that is missing is a scale slider for the size of the controls. It would be nice to make them smaller for larger screens.

**Comment by Tajnymag** [comment]
I second that

**Comment by mittorn** [comment]
You need press edit button and change size off all controls manually. Maybe we'll add presets for different screen sizes later, like it is in cs16client now.

**Comment by The-MAZZTer** [comment]
I didn't see any way to change the sizes, I'll have to go back and check again. Regardless, I would suggest looking at something like how Nova Launcher handles widget moving and resizing for inspiration.

**Comment by mittorn** [comment]
Use two fingers in editing mode to resize button.

**Comment by a1batross** [comment]
Not a bug.
