### ISSUE TITLE
Capturing Mouse Positions

### ISSUE THREAD

**Issue by Trackcl** [FWGS/xash3d-android-project#87]
I bought a USB OTG, but does not capture the mouse movement :C

**Comment by RicardF** [comment]
Is there any way to make the mouse movement working?

**Comment by mittorn** [comment]
Yes, but only if you have root.
use evdev_nousepath to specify evdev device path
Use evdev_mouseopen to turn on mouse
Use evdev_grab 1 to enable event grab
Simple script to try open last connected device (save as evdev.cfg in valve folder):
```
evdev_mousepath /dev/input/event10;evdev_mouseopen
evdev_mousepath /dev/input/event9;evdev_mouseopen
evdev_mousepath /dev/input/event8;evdev_mouseopen
evdev_mousepath /dev/input/event7;evdev_mouseopen
evdev_mousepath /dev/input/event6;evdev_mouseopen
evdev_mousepath /dev/input/event5;evdev_mouseopen
evdev_mousepath /dev/input/event4;evdev_mouseopen
evdev_mousepath /dev/input/event3;evdev_mouseopen
evdev_mousepath /dev/input/event2;evdev_mouseopen
evdev_mousepath /dev/input/event1;evdev_mouseopen
evdev_mousepath /dev/input/event0;evdev_mouseopen
```

**Comment by mittorn** [comment]
It is possible to implement mouse support without root on some nvidia devices, it has API extension for it.
I'll try to implement it later.

**Comment by Trackcl** [comment]
I was doing the steps that you mentioned which would be the following (i have root):
1)
![evdev](https://cloud.githubusercontent.com/assets/15820799/14696222/a9b25a92-074f-11e6-9285-4841bbc182f4.JPG)
2)
![event2](https://cloud.githubusercontent.com/assets/15820799/14696231/b7a0b9dc-074f-11e6-8064-a299ca2d3400.JPG)
3)
![13078068_10207926901624907_527513773_o](https://cloud.githubusercontent.com/assets/15820799/14696237/bf46b8b2-074f-11e6-9ebe-41734b03fbbb.png)

In game, the mouse pointer appears, but i only can shoot.


thanks for the help :)

**Comment by mittorn** [comment]
Use
`exec evdev.cfg`
to use config.
enter evdev_grab 1 to lock mouse pointer

**Comment by Trackcl** [comment]
nothing u.u. 
Only can shoot with the mouse.
PD: evdev_grab 1 not works

**Comment by a1batross** [comment]
Are you trying to use mouse in CS16Client?
It will not work with CS, because it's blocked due to disbalance in
multiplayer.

**Comment by Jan200101** [comment]
Actually there is a way to scan for mouse input without root by using air view

**Comment by DeicPro** [comment]
@a1batross Does multiplayer work? I thought that didn't work, because I can't join in any server never :P

**Comment by a1batross** [comment]
@DeicPro multiplayer works. But here is some limitations for Xash3D.
* No servers. Yes, we have some servers, but most of it is located in Russia, which is unacceptable to others due to VERY high ping.
* Xash3D is written only for singleplayer. The author of Xash3D(Uncle Mike) says that multiplayer is a "miracle".
* Due to protocol problems there is some limitations on random WiFi routers during connect. But workaround is available! Try set cl_maxpacket to low value. For example, 1000 or 700. 

If you can set up a server, read this article: https://github.com/SDLash3D/xash3d/wiki/How-to-set-up-a-Xash3D-Dedicated-Server-on-Debian-or-Ubuntu

**Comment by Jan200101** [comment]
@a1batross Quick  question how do you get your server on the master server list ? (you know the one where you go on internet games) my server is online and working but it doesnt show up on there

**Comment by a1batross** [comment]
@Jan200101 If your computer is under NAT, you must open ports on your
router. (google it)
Or have a "white" IP, i.e. without NAT.

2016-05-14 21:12 GMT+03:00 Jan200101 <notifications@github.com>:

**Comment by Jan200101** [comment]
@a1batross I already did that and my Server works outside my network but It wont show up in the master server list

**Comment by a1batross** [comment]
@Jan200101 try set "public 1" in server.cfg

**Comment by Jan200101** [comment]
@a1batross worked without testing... I noticed when around 5 people joined it xD

**Comment by doritmtm** [comment]
i wrote this in the evdev.cfg
evdev_mousepath /dev/input/event10;evdev_mouseopen;evdev_mousepath /dev/input/event9;evdev_mouseopen;evdev_mousepath /dev/input/event8;evdev_mouseopen;evdev_mousepath /dev/input/event7;evdev_mouseopen;evdev_mousepath /dev/input/event6;evdev_mouseopen;evdev_mousepath /dev/input/event5;evdev_mouseopen;evdev_mousepath /dev/input/event4;evdev_mouseopen;evdev_mousepath /dev/input/event3;evdev_mouseopen;evdev_mousepath /dev/input/event2;evdev_mouseopen;evdev_mousepath /dev/input/event1;evdev_mouseopen;evdev_mousepath /dev/input/event0;evdev_mouseopen;evdev_grab 1;
And it worked succesfully to me
i saw in the given code for the cfg at the end of any line there missing ;
Put those missing ; and worked succesfully
i only needed to exec evdev.cfg and the mouse started to work

**Comment by Recee23** [comment]
So is there any way to use mouse without root?

**Comment by mittorn** [comment]
@doritmtm look at https://github.com/FWGS/xash3d-android-project/issues/87#issuecomment-212506244
It has line breaks.

**Comment by a1batross** [comment]
@Recee23 
It is possible now on every NVIDIA SHIELD device(they does have mouse extension). And must be working for Android 7.x.

**Comment by Recee23** [comment]
??

**Comment by kuwoh** [comment]
sorry to bump this but it doesnt seem to work :/ tested on rooted device
