### ISSUE TITLE
Android SD card location

### ISSUE THREAD

**Issue by Dancanplay** [FWGS/xash3d-android-project#88]
Whenever I select SD card location, path stays at internal storage(/storage/emulated/0/xash3D).

**Comment by fuzun** [comment]
Do you have samsung phone?

**Comment by a1batross** [comment]
Use the advanced File Manager, like FX File Manager or ES, which will give
you full path to the folder with games.
Copy the path from FM and paste it in Xash3D Launcher.

Selector is only for read/write permissions introduced in Lollipop.

2016-04-22 20:51 GMT+03:00 fuzun <notifications@github.com>:

**Comment by Dancanplay** [comment]
No, using Xperia Z1 Compact.

**Comment by fuzun** [comment]
@a1batross It is not working, and it was the reason of my now-gone pull request.
I doubt if it can fully operate exteral storage without touching native xash3d. Some says it needs file descriptors to utilize files.

I am now opening a new issue regarding this problem, and continue to work on this subject at there.

**Comment by a1batross** [comment]
FPicker was introduced in 0.18, so it's must be more easier to select proper folder.
