### ISSUE TITLE
External Storage Problems

### ISSUE THREAD

**Issue by fuzun** [FWGS/xash3d-android-project#89]
- Below kitkat, no problem.
- **kitkat** -> It is not possible to do anything regarding this issue. Don't use kitkat if you concern about storage.
- **lollipop** -> It is possible to make this application utilize external storage, but this method needs some android specific code and modification for native engine.
- **marshmallow** -> I don't have any clue for this version. But there should not be any problem if you adopt the external storage. If you dont adopt, you must wait for a fix. And fix for lollipop should fix for marshmallow as well.

After opening selector (Opening it may not affect anything for this app), app works without "-dev and -log". But it can not do some essential file operations such as saving the game.
If you try to launch it with -dev and -log at same time, it will pop up a messagebox showing errors.

Also, there is a problem about getting the exact location. getExternalStorageDirectory().getPath() this returns wrong path. Is not it possible to get the exact path with uri? Maybe faking it with a file?

On the other hand, why this app does not have write access permission in manifest file?

I think all of these issues should be gone if **SAF** gets integrated into this project properly.

**Comment by a1batross** [comment]
Maybe change the default path to the new location, e.g. Android/data/in.celest.xash3d.hl. 
I think, with permission, app can everytime write files to this directory. 

>On the other hand, why this app does not have write access permission in manifest file?
https://github.com/SDLash3D/xash3d-android-project/blob/master/AndroidManifest.xml#L95

>After opening selector (Opening it may not affect anything for this app), app works without "-dev and -log". But it can not do some essential file operations such as saving the game.
Removing -dev -log isn't a solution! Don't even say about it.
Better to crash while starting, if we can't write to the FS.

**Comment by fuzun** [comment]
Hmm. It seems that I forget that line or maybe new commit arrived.
But any way it just do not work correctly (excluding the one case I specified below), I even tried after gaining persistent permissions for sd card root folder but no luck. It kept giving errors or crashes. The problem is not with java side-the launcher, it is about xash3d. It works with classic fopen but I read somewhere on the internet that says it must be done with file descriptors. I don't have an exact idea about how it should be implemented though.

"Android/data/in.celest.xash3d.hl" I tried this location 2-3 months ago and it worked, as I could save the game and log it.
However, the main problem with this location is that it is just a 'data' storage, a place where you keep settings, small assets and other stuff. The concept of this xash3d android project is different in contrast. It is *like* a emulator that you tell where the game is located and it launches it, emulators do not include game files hence they dont use their dedicated storage for game/resource storage.
Also, there is a problem with that specific directory. It is that if you remove the app, game resources get removed as well.

> Removing -log isn't a solution! Don't even say about it.

Thats what I am talking about. -log or other parameters is not the problem, the problem is that this is a android project but it suffers from some retarded android problems. As I said, I think SAF should be properly adopted as a workaround for this particular issue.

**Comment by a1batross** [comment]
In 0.19 using non-writable storage is prohibited.Testing engine builds introduce "RoDir" feature: connect any directory as a read-only base directory. So setting -rodir "/extsdcard/xash" in command line will force engine use read-only resources from that directory, but write config files, saverestore data somewhere else.
--
