### ISSUE TITLE
Xash Error: Sys_Crash

### ISSUE THREAD

**Issue by omgitsdark** [FWGS/xash3d-android-project#90]
So I wanted to try CSStrikeClient 1.6 (1.0 release) on my Galaxy S5 (Lollipop) and everything went smooth except for playing with bots. Whenever I create a game with bots Xash crashes a minute later, showing this error and it gets stuck there:
http://i.imgur.com/aZTwtv8.png

**Comment by a1batross** [comment]
Which bots? Attach a log and more info about your actions.

**Comment by omgitsdark** [comment]
I'm using YaPB bots. Where do I get logs from? Should I use Catlog?

**Comment by a1batross** [comment]
Rerun engine with -log and attach an engine.log.

Catlog will be good too.

2016-04-25 19:16 GMT+03:00 omgitsdark <notifications@github.com>:

**Comment by roshanray** [comment]
Sync error what to do
