### ISSUE TITLE
Black screen or not responding screen

### ISSUE THREAD

**Issue by Galotex** [FWGS/xash3d-android-project#92]
Sorry for my bad english

When i had the samsung galaxy s4 mini it worked just fine, but now i have the samsung galaxy s6 edge and the game doesn't respond at all, i can hear when i press buttons and somehow interact with them, but the screen doesn't update, i really want to play counter strike on mi mobile and this issue is really annoying, please help :(

**Comment by Galotex** [comment]
https://www.youtube.com/watch?v=UQFBXEmyPxI
Here's an  example

**Comment by a1batross** [comment]
It's a problem of Galaxy S6.

**Comment by a1batross** [comment]
Maybe it was fixed since then. If S6 still causes such problems, create new issue.
